### ISSUE TITLE
(feat) device-init.yaml schema documentation

### ISSUE THREAD

**Issue by denzuko** [hypriot/device-init#46]
As an DevOps engineer
I would like to verify my device-init with a yaml schema file via a tool like yamale
So that I can generate a few different configurations with cookiecutter 
And so that I can pass these device configurations to flash as a CICD build asset

**Comment by denzuko** [comment]
I'll be glad to include the implementation as part of the DevOpsCast stream if there isn't already existing documentation. But need this for the PR.

Before I go down that route; is there an established schema or does the go unit tests basically sum up the expected data?

**Comment by firecyberice** [comment]
We deprecated device-init in favor of cloud-init about 4 years ago .
Sorry for missing to add a note to the repository.
