### ISSUE TITLE
Setting timezone

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/device-init#8]
Idea from https://github.com/hypriot/flash/issues/53, flash could help using the same timezone from host Mac/Linux PC.

**Comment by alexellis** [comment]
Either from host - or just specified in YAML - i.e. CET for most of Hypriot team and Europe/London for UK etc. Very useful to have as part of config.

**Comment by StefanScherer** [comment]
Closing as we switch over to cloud-init/cloud-config's user-data file.
